### PR TITLE
Add reactor uc

### PR DESCRIPTION
**Pull request by LasseRosenow**
Initial draft (scripts still don't work)

`make all` in root should work after lfcg was run

### CODE REVIEW

**Review by erlingrj — APPROVED** [review]
This looks reasonable to me!

**Comment by LasseRosenow** [comment]
I have removed the scripts for now and greatly simplified the Makefile, by moving things over to `riot.mk` in `reactor-uc` see: https://github.com/lf-lang/reactor-uc/pull/166

I noticed a chicken-egg issue though.
Right now the LFC copies `reactor-uc` into the `src-gen` folder.
But without reactor-uc already available somewhere else we cannot use the LFC in the first place, as it is part of reactor-uc.

That is why for now I depend on the `REACTOR_UC_PATH` variable to be set to build this example.
Inside `riot.mk` we can then get the LFC path based on the `REACTOR_UC_PATH` variable.

What about we include reactor-uc just as a top-level submodule? maybe together with `RIOT` in a `deps` folder, or just on root.
This way this all would work out of the box and REACTOR_UC_PATH would be very clear as well.

**Comment by erlingrj** [comment]
@LasseRosenow, will you tag me for a review again after making modifications as discussed in today's meeting?

**Comment by LasseRosenow** [comment]
@erlingrj Ready for review again

**Comment by erlingrj** [comment]
This looks great. I have given you write access to the repo so you can push PRs directly to this instead of a fork

**Review by erlingrj — APPROVED** [review]

**Pull request merged**
